LPS-163136 Add commons-io to batch-service-engine
Added commons-io in order to resolve test failures introduced by updating POI/POI-OOXML.

Error from Test Failures:
Caused by:
        java.lang.ClassNotFoundException: org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream